CREATE SCHEMA IF NOT EXISTS EMPRESA;
USE EMPRESA;

DROP TABLE IF EXISTS DEPARTAMENTOS;
CREATE TABLE IF NOT EXISTS DEPARTAMENTOS(
    NUMERO INT,
    NOMBRE VARCHAR(25) NOT NULL,
    NSS VARCHAR(15) NULL,
    FECHA DATE NULL,
    PRIMARY KEY(NUMERO)
    );
    
DROP TABLE IF EXISTS PROYECTOS;
CREATE TABLE IF NOT EXISTS PROYECTOS(
    NUMERO INT,
    NOMBRE VARCHAR(25) NOT NULL,
    LUGAR VARCHAR(25) NOT NULL,
    DEPARTAMENTO INT NOT NULL,
    PRIMARY KEY(NUMERO),
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTOS(NUMERO)
    );
    
DROP TABLE IF EXISTS EMPLEADOS;
CREATE TABLE IF NOT EXISTS EMPLEADOS(
    NOMBRE VARCHAR(25) NOT NULL,
    APELLIDO1 VARCHAR(25) NOT NULL,
    APELLIDO2 VARCHAR(25) NOT NULL,
    NSS VARCHAR(15) NOT NULL,
    CALLE VARCHAR(30) NULL,
    NUMERO_CALLE INT NULL,
    PISO VARCHAR(4) NULL,
    CP VARCHAR(5) NULL,
    LOCALIDAD VARCHAR(25) NULL,
    FECHA_NACIMIENTO DATE NULL,
    SALARIO FLOAT NULL,
    SEXO CHAR(1) NULL,
    SUPERVISOR VARCHAR(15) NULL,
    DEPARTAMENTO INT NULL,
    PRIMARY KEY(NSS),
    FOREIGN KEY (SUPERVISOR) REFERENCES EMPLEADOS (NSS),
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTOS (NUMERO)
    );

DROP TABLE IF EXISTS EMPLEADOS_PROYECTOS;
CREATE TABLE IF NOT EXISTS EMPLEADOS_PROYECTOS(
    EMPLEADO VARCHAR(15),
    PROYECTO INT NOT NULL,
    HORAS INT NULL,
    PRIMARY KEY(EMPLEADO,PROYECTO),
    FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS(NSS),
    FOREIGN KEY (PROYECTO) REFERENCES PROYECTOS(NUMERO)
    );

ALTER TABLE DEPARTAMENTOS
    ADD FOREIGN KEY (NSS) REFERENCES EMPLEADOS (NSS);

    
DELIMITER //

CREATE PROCEDURE pr_cambioDomicilio(
    IN p_nss VARCHAR(10),
    IN p_calle VARCHAR(50),
    IN p_numero_calle INT,
    IN p_piso VARCHAR(10),
    IN p_cp VARCHAR(10),
    IN p_localidad VARCHAR(50)
)
BEGIN
    UPDATE EMPLEADOS
    SET CALLE = p_calle,
        NUMERO_CALLE = p_numero_calle,
        PISO = p_piso,
        CP = p_cp,
        LOCALIDAD = p_localidad
    WHERE NSS = p_nss;
END //

CREATE PROCEDURE pr_DatosProxectos(
    IN p_numero INT,
    OUT p_nombre VARCHAR(50),
    OUT p_lugar VARCHAR(50),
    OUT p_departamento INT
)
BEGIN
    SELECT NOMBRE, LUGAR, DEPARTAMENTO
    INTO p_nombre, p_lugar, p_departamento
    FROM PROYECTOS
    WHERE NUMERO = p_numero;
END //

CREATE PROCEDURE pr_DepartControlaProxec (IN NUMEROPROY INT)
BEGIN
    SELECT D.NUMERO, D.NOMBRE, D.NSS, D.FECHA
    FROM DEPARTAMENTOS AS D
    WHERE (SELECT COUNT(*) FROM PROYECTOS WHERE DEPARTAMENTO = D.NUMERO) >= NUMEROPROY;
END //

CREATE FUNCTION fn_nEmpDepart (NOMBRE VARCHAR(25))
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE DEP INT;
    SELECT NUMERO INTO DEP FROM DEPARTAMENTOS as d WHERE d.NOMBRE = NOMBRE;
    RETURN (SELECT COUNT(*) FROM EMPLEADOS WHERE DEPARTAMENTO = DEP);
END //

DELIMITER ;
